### ISSUE TITLE
Find a way to test the initialization of the registry's domain separator

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/stealth-address-erc-contracts#6]
See https://github.com/ScopeLift/stealth-address-erc-contracts/pull/5/commits/a5b3e4db42c7230a4ae1eab0e8bca6c723c0ea1d#r1471961987 for context

**Comment by garyghayrat** [comment]
Solved using a [test harness](https://github.com/ScopeLift/stealth-address-erc-contracts/blob/8131727b53b3d9051ee1e576d332d8f3b7e2e716/test/ERC6538Registry.t.sol#L60-L69) and added the [tests here](https://github.com/ScopeLift/stealth-address-erc-contracts/blob/8131727b53b3d9051ee1e576d332d8f3b7e2e716/test/ERC6538Registry.t.sol#L71-L84).
